#!/bin/bash

set -e

pushd "$(dirname "$0")" > /dev/null
SCRIPT_DIR="$(pwd)"
popd > /dev/null
TGT_DIR=$SCRIPT_DIR/tgt

rm -rf "$TGT_DIR"
mkdir -p "$TGT_DIR"
clang -O2 -fwrapv -Wall -framework Foundation -framework CoreMIDI -o "$TGT_DIR"/midimap \
	"$SCRIPT_DIR"/midimap.m
